# Generated by Django 6.0.6 on 2026-06-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('eliminado', 'Eliminado')], default='activo', max_length=20),
        ),
    ]
