# Generated by Django 6.0.6 on 2026-07-18 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_delete_systemactivitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productactionlog',
            old_name='admin',
            new_name='actor',
        ),
    ]
