# Generated by Django 6.0.6 on 2026-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos_detalle',
            field=models.TextField(blank=True, default=''),
        ),
    ]
