# Generated by Django 6.0.7 on 2026-07-21 03:13

from django.db import migrations, models


def migrar_pedidos_confirmados(apps, schema_editor):
    Pedido = apps.get_model('marketplace', 'Pedido')
    Pedido.objects.filter(estado='confirmado').update(estado='preparando')


def revertir_pedidos_preparando(apps, schema_editor):
    Pedido = apps.get_model('marketplace', 'Pedido')
    Pedido.objects.filter(estado='preparando').update(estado='confirmado')


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_pedido_productos_detalle'),
    ]

    operations = [
        migrations.RunPython(
            migrar_pedidos_confirmados,
            revertir_pedidos_preparando,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando pedido'), ('listo', 'Listo para retiro'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
