# Generated by Django 6.0.7 on 2026-07-21 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_pedido_productos_detalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTransferenciaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Cuenta corriente'), ('vista', 'Cuenta vista'), ('ahorro', 'Cuenta de ahorro'), ('rut', 'Cuenta RUT')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_transferencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
