# Generated by Django 6.0.7 on 2026-07-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_alter_pedido_estado'),
        ('marketplace', '0018_datos_transferencia_y_estado_preparando'),
    ]

    operations = [
    ]
