# Generated by Django 6.0.6 on 2026-07-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
