# Generated by Django 6.0.6 on 2026-07-20 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_pedido_productos_detalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en_camino', 'En camino'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor'), ('delivery', 'Delivery')], max_length=20),
        ),
    ]
