# Generated by Django 6.0.6 on 2026-07-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_pedido_estado_entrega_pedido_repartidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('no_entregado', 'No entregado')], default='pendiente', max_length=20),
        ),
    ]
